### ISSUE TITLE
The implementation of Eq.(8)

### ISSUE THREAD

**Issue by kunkun0w0** [liren2515/DIG#3]
Hi Ren Li!
Thanks for releasing such awesome work. 
But I am a little confused about the implementation of the blending model for the garment, i.e., Eq.(8). 
It seems like the shape-related blend shape and skinning weight of the SMPL model will share the same weights in the paper.
![image](https://user-images.githubusercontent.com/56219029/221350397-cabbc303-4276-4d2d-91fb-4b6885e78229.png)

However, I find that DIG directly uses the MPL output to predict the skinning weights for the joints both in the training code and inference code.
https://github.com/liren2515/DIG/blob/41ee173e4656c17ce3eed349669643f37f89453f/utils/deform.py#L96
https://github.com/liren2515/DIG/blob/41ee173e4656c17ce3eed349669643f37f89453f/models/model_skinning.py#L203

Additionally, I notice that when processing the shape-related blend shape, DIG also multiplies a tensor called `tfs_weighted_zero`. 
But I fail to figure out the meaning of this parameter and it also doesn't exist in the `SMPLServer`.
https://github.com/liren2515/DIG/blob/41ee173e4656c17ce3eed349669643f37f89453f/utils/deform.py#L91

Would you like to share more instructions of DIG? thanks!

**Comment by liren2515** [comment]
Thanks for your interest in our work.

Yes, the skinning part in the released code is a bit of different from the original one. But theoretically they are similar and the idea is the same, using the diffused version of blending weights and shapes.

As for `tfs_weighted_zero`, it should be the inverse of `tfs_c_inv`. Since the garment (CLOTH3D) we are using is draped on a TA-pose body instead of the T-pose body (whose pose parameters are 0s), we need to rotate vertices back to the T-pose space first by `tfs_c_inv` and then rotate them to the target pose by `tfs`. `tfs_weighted_zero` is used for the correction on the blending shape.

**Comment by kunkun0w0** [comment]
Thanks for your kind explanation!
